### ISSUE TITLE
gridZ coordinate is always "zero" for Livonia map

### ISSUE THREAD

**Issue by Yzoop** [antihax/RadioNotifications#2]
Hello,
Thanks for a great mod, it works perfectly fine and I'm amazed you did it.

But I've recently discovered a bug, which can be reproduced: 
1. set phonetics 130 in json, or any other phonetics, which takes coordinates gridX and gridZ, 
2. wait for the voice radio message
3. the radio message only contains full gridX, but for gridZ it's only "zero".

The bug was only discovered on livonia map.

Here's an example of the json I have:
```json
{
    "version": 1,
    "maxDistance": 9000,
    "baseRadioMultiplier": 1.5,
    "ignoreDistance": 500,
    "minVolume": 0.30000000149011612,
    "maxVolume": 1.0,
    "radioChannel": 0,
    "randomNoise": 0,
    "disablePlayerBroadcast": 1,
    "eventMap": {
        "Wreck_UH1Y": {
            "preamble": 1,
            "voice": 0,
            "noise": 2,
            "signature": 1,
            "phonetics": [
		131
            ],
            "pause": 2,
            "delay": 60,
            "repeat": 40,
            "message": ""
		}
    },
    "staticEvents": [],
    "alarmMap": {
        "ContaminatedArea_Dynamic": {}
    },
    "staticAlarms": []
}
```

**Comment by antihax** [comment]
Fixed with 55d861b59cd013cd2f0e5769322b9c40e165eaf3
